In [4]:
# 경고 무시
import warnings
warnings.simplefilter('ignore')

# 자주 사용하는 패키지를 임포트
import matplotlib as mpl
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import sklearn as sk

# matplotlib 설정
mpl.use('Agg')

# seaborn 설정
sns.set()
sns.set_style("whitegrid")
sns.set_color_codes()


In [7]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7])
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
type(ar)

numpy.ndarray

In [9]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
answer = []
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
x = np.array(data)
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# 연습 문제 1
k = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
k

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [13]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array


In [14]:
d.ndim

3

In [16]:
d.shape

(2, 3, 4)

In [17]:
# 연습문제 2
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])


In [18]:
m[1, 2]

7

In [20]:
m[2,4]

14

In [21]:
m[1, 1:3]

array([6, 7])

In [23]:
m[1:, 2]

array([ 7, 12])

In [24]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [25]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [26]:
# 연습문제 3
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


In [29]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [30]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [33]:
x[(x % 4 == 1) & (x % 3 == 0)]

array([9])