In [3]:
# 경고 무시
import warnings
warnings.simplefilter('ignore')

# 자주 사용하는 패키지를 임포트
import matplotlib as mpl
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import sklearn as sk

# matplotlib 설정
mpl.use('Agg')

# seaborn 설정
sns.set()
sns.set_style("whitegrid")
sns.set_color_codes()


In [1]:
print("G")

G


In [12]:
# 연습문제 3.2.1
x = np.array([0, 0, 0, 1, 1], dtype=float)

In [13]:
np.tile(x, (3, 1))

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [17]:
u = np.array([10, 20, 30, 40, 50])
u+50

array([ 60,  70,  80,  90, 100])

In [18]:
np.vstack([x, u])

array([[ 0.,  0.,  0.,  1.,  1.],
       [10., 20., 30., 40., 50.]])

In [24]:
np.tile(np.vstack([np.vstack([np.vstack([np.tile(x, (3, 1)),u]), u+50]), u+100]),(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [27]:
x = np.arange(3)

In [28]:
x

array([0, 1, 2])

In [29]:
y = np.arange(5)

In [30]:
y

array([0, 1, 2, 3, 4])

In [31]:
X, Y = np.meshgrid(x, y)
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [32]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [36]:
mus = [list(zip(x, y)) for x, y in zip(X, Y)]

In [37]:
mus

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]